### ISSUE TITLE
Add COSMOS public key fingerprints to docs

### ISSUE THREAD

**Issue by valentinaschueller** [lunarc/lunarc_docs#27]
The first time users connect to COSMOS, they will be asked to verify the SSH key signature. I think it would be great to add them to the Getting Started guide (e.g., the [How to login page](https://lunarc-documentation.readthedocs.io/en/latest/getting_started/login_howto/)), cf. [GitHub's](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints) or [NSC's](https://nsc.liu.se/support/getting-started/) equivalents.

**Comment by jonaslindemann** [comment]
Good idea. I will ask the team to add this.
