### ISSUE TITLE
Request password: add waiting time

### ISSUE THREAD

**Issue by richelbilderbeek** [lunarc/lunarc_docs#28]
I found the documentation to reset a LUNARC password at [https://lunarc-documentation.readthedocs.io/en/latest/intro/lost_password/](https://lunarc-documentation.readthedocs.io/en/latest/intro/lost_password/) and was able to reset a password.

What I missed is an expected time before the new password is actually active. As far as I can see now, it is not instantaneous. But is it minutes, hours, overnight when the password gets updated?

As I predict I am not the only user, I hope the answer gets added to the documentation.

**Comment by markgyver** [comment]
Hi.

I updated the documentation.
 If you have problems login in even after changing the password one reason can be the lack of an active pocket pass token registered in the system.

Regards
Marcos

**Comment by richelbilderbeek** [comment]
Thanks @markgyver! Fun we that just talked :-)
