### ISSUE TITLE
Suggest: add waiting time when resetting password

### ISSUE THREAD

**Issue by richelbilderbeek** [lunarc/lunarc_docs#29]
This Issue is similar in request as #28. That Issue was closed, without any clear reply if this will or will not be added to the documentation. Taking a look at the documentation, it has not been added. Or not been added yet, I don't know. I don't know if it will be added to the documentation yes or no. And the option to re-open an Issue is disabled (no idea why). Hence again this suggestion:

I found the documentation to reset a LUNARC password at https://lunarc-documentation.readthedocs.io/en/latest/intro/lost_password/ and was able to reset a password.

What I missed is an expected time before the new password is actually active. I understand from @markgyver that this is instantaneous. As I predict I am not the only user, I hope the answer gets added to the documentation.

I volunteer to add this information by a Pull Request too :+1:

**Comment by markgyver** [comment]
It takes time to get the changes made in the git repository to be published on the documentation page through readthedocs. The changes are not automatically published.

**Comment by richelbilderbeek** [comment]
Great, well done! Thanks @markgyver, it was useful immediately too :+1:
