### ISSUE TITLE
Suggest: add link to GitHub repo and/or a CONTRIBUTE document

### ISSUE THREAD

**Issue by richelbilderbeek** [lunarc/lunarc_docs#30]
I like the LUNARC documentation and its choice to use MkDocs. Finding support is clear too, well done!

I do think it is needlessly complicated to (1) find the GitHub repo with its content (and Issues), and (2) find out how to contribute. 

I assume contributions from users are welcomed (at UPPMAX, we enjoy these!) and I assume LUNARC cares about its users too. 

So, what we did:

- At [the UPPMAX documentation](https://docs.uppmax.uu.se/) (top-right corner) there is always a link to the repository.
- At [the UPPMAX documentation's support page](https://docs.uppmax.uu.se/support/) there is a link to how to contribute, which is [a standard-named CONTRIBUTING.md document](https://github.com/UPPMAX/UPPMAX-documentation/blob/main/CONTRIBUTING.md)

Could the LUNARC doc add a link to GitHub repo and/or a CONTRIBUTE document, so that users its users feel (even more) welcome to contribute?

I volunteer to do (with stub content) so with a Pull Request.

**Comment by jonaslindemann** [comment]
Fixed in next commit. Added a CONTRIBUTING.md and a link on the documentation pages.
