### ISSUE TITLE
Share video on how to login?

### ISSUE THREAD

**Issue by richelbilderbeek** [lunarc/lunarc_docs#33]
Dear LUNARC colleagues,

I've made a video on how to login to COSMOS using SSH, including a password reset and a Pocket Pass reset, at [https://youtu.be/sMsenzWERTg ](https://youtu.be/sMsenzWERTg ). I think it is a good complement to the existing documentation.

Feel free to yes/no link to it.

I'd happily send over the original files. 

I also volunteer to add it to the documentation using a Pull Request :+1:

**Comment by jonaslindemann** [comment]
You are welcome to contribute using a pull request. Then we can review it and see how it would integrate.

**Comment by richelbilderbeek** [comment]
@jonaslindemann this is great! Thanks for accepting my suggestions! I will use PRs from now on :+1:
