### ISSUE TITLE
Suggest: let GitHub repo link to MkDocs pages in main page

### ISSUE THREAD

**Issue by richelbilderbeek** [lunarc/lunarc_docs#34]
Dear LUNARC colleagues,

Thanks for putting your documentation publicly online.

Currently, there is no clear visible link between the GitHub repo to the documentation pages:

![Screenshot from 2024-10-21 10-36-05](https://github.com/user-attachments/assets/b1ccacc1-df7b-4f51-9344-6f350b08a814)

Note the absence of the link to [https://lunarc-documentation.readthedocs.io/](https://lunarc-documentation.readthedocs.io/) in the top-right corner, where the general info about a repo is found.

As an example. at UPPMAX we do have it:

![Screenshot from 2024-10-21 10-36-19](https://github.com/user-attachments/assets/55a991f0-631f-4ef9-b9f7-201abcac5761)

I suggest to clearly show the link to https://lunarc-documentation.readthedocs.io/ from the project info, as it is the standard place to do so.

Goal is that users find the documentation even when landing on the GitHub repo first.

**Comment by jonaslindemann** [comment]
Added to github now.
